# Basic GitHub Actions Pipeline for Kong Konnect demonstrating the canary release plugin
#
# Author: David MacDonald
# Contact: david.macdonald@konghq.com
# Website: https://konghq.com/
#
# DISCLAIMER: DO NOT USE THIS IN PRODUCTION - FOR DEMONSTRATION PURPOSES ONLY
#

name: CI

on:

  push:
    branches: 
      - main

  workflow_dispatch:

jobs:

  deploy-api:
    runs-on: ubuntu-22.04
    name: Deploy API to Kong Konnect Control Plane
    steps:        
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Install decK tool
      run: |
        curl -sL https://github.com/kong/deck/releases/download/v1.38.1/deck_1.38.1_linux_amd64.tar.gz -o deck.tar.gz
        tar -xf deck.tar.gz -C /tmp
        sudo cp /tmp/deck /usr/local/bin/

    - name: Verify connectivity with Kong Konnect
      run: deck gateway ping --konnect-addr https://eu.api.konghq.com --konnect-token ${{ secrets.KONNECT_ACCESS_TOKEN }} --konnect-control-plane-name ${{ secrets.KONNECT_CONTROL_PLANE }}

    - name: Validate Kong declarative configuration
      run: deck file validate kong.yaml
    
    - name: Diff existing configuration vs new configuration
      run: deck gateway diff kong.yaml --konnect-addr https://eu.api.konghq.com --konnect-token ${{ secrets.KONNECT_ACCESS_TOKEN }} --konnect-control-plane-name ${{ secrets.KONNECT_CONTROL_PLANE }}
    
    - name: Backup existing Kong configuration
      run: deck gateway dump --konnect-addr https://eu.api.konghq.com --konnect-token ${{ secrets.KONNECT_ACCESS_TOKEN }} --konnect-control-plane-name ${{ secrets.KONNECT_CONTROL_PLANE }} --select-tag use-case-1 -o kong-backup.yaml
    
    - name: Upload Kong backup to artifact repository
      uses: actions/upload-artifact@v3
      with:
        name: kong-backup
        path: kong-backup.yaml
    
    - name: Deploy new declarative configuration to Kong
      run: deck gateway sync --konnect-addr https://eu.api.konghq.com --konnect-token ${{ secrets.KONNECT_ACCESS_TOKEN }} --konnect-control-plane-name ${{ secrets.KONNECT_CONTROL_PLANE }}
